### ISSUE TITLE
Étudier une offre d'hébergement Wordpress et essayer de trouver l'offre d'hébergement que je choisierai

### ISSUE THREAD

**Issue by stephane-klein** [harobed/personnal-notebook#344]
J'ai une ou deux fois par an, un ami qui me demande mon avis à props du tarif d'une offre d'hébergement de site web, dans 80% c'est pour héberger du Wordpress.

Dans la plupart des cas, j'ai donné une réponse peu qualitative, sans valeur ajouté. En gros, du smalltalk, une réponse de comptoire de bar, sans argument.

Je souhaite, cette fois, essayer de donner une réponse argumentée à mon ami.

Je souhaite aussi transformer cette réponse en un article de blog, que je pourrais à l'avenir donner en réponse à ce type de question.

## Ressources

Voici ce que me dit [Wappalizer](https://www.wappalyzer.com/) à propos du site hébergé :

<img src="https://github.com/stephane-klein/backlog/assets/54498080/77f1af5d-2ca7-43ba-9850-bd83e7deee18" width="400" />

Contenu de l'offre d'hébergement :

<img src="https://github.com/stephane-klein/backlog/assets/54498080/14311094-2af2-428e-b4f0-ef10815d14cd" width="1200" />

## Todo

- [x] Aller chercher le prix et le contenu de l'offre d'hébergement mutualisé de OVH
- [x] Aller chercher le prix et le contenu de l'offre Mailjet
- [ ] Calculer le coût que le presta reverse sur l'année à OVH et Mailjet
- [ ] Calculer sa marge brut (avant salaire)
- [ ] Étudier les offres d'hébergement fourni par Wordpress
- [ ] Commenter :
  - [ ] La partie certificat SSL (j'ai vérifié, le site certificat [Let's Encrypt](https://fr.wikipedia.org/wiki/Let%27s_Encrypt) gratuit (c'est bien mais il est facturé))
- [ ] Rédiger un paragraphe avec les sujets suivants :
  - [ ] J'ai dû faire de nombreuses fois cet exercice de rédaction d'offre d'hébergement
  - [ ] Souvent, je pars du montant que je souhaite facturer et ensuite j'essaie de mettre des choses dans l'offre pour justifier le prix
  - [ ] …
- [ ] Rédiger un paragraphe pour expliquer que l'offre d'hébergement va de pair avec l'offre de création du site et sa maintenance, souvent c'est lié
- [ ] Expliquer ce que je ferais si je suis à la place du maitre d'ouvrage

**Comment by stephane-klein** [comment]
Page qui liste les hébergements web mutualisés de OVH : https://www.ovhcloud.com/fr/web-hosting/

**Comment by stephane-klein** [comment]
[L'offre à 2,30 € HT / mois de OVH](https://www.ovhcloud.com/fr/web-hosting/personal-offer/) comprend 100 Go d'espace disque, 10x plus que ce que contient l'offre d'hébergement ci-dessus, doit 27,60 € HT/an.

Je n'ai pas fait de test, mais je pense par expérience que cette offre doit être lente, surtout lors du premier accès au site. Je pense que ce site est plutôt hébergé sur un serveur dédié à d'agence web, où elle mutualise un certain nombre de sites web qu'elle héberge.

Il existe un large éventail de prix de serveur dédié, qui commencent aux alentours de 30 €. Je vais partir arbitrairement sur un serveur à 100 € par mois, qui héberge 100 sites Wordpress. Ce qui fait 12 € / an par site web.

> Mailjet… jusqu'à 20 000 mails / an

Si je regarde [les tarifs Mailjet](https://www.mailjet.com/fr/tarifs/), je lis 0 € pour 6000 mails / mois, soit 0 € pour 72 000 mails par an.

Je pense que la marge brut (dont sans compter le salaire de la prestation) de cet hébergement est de 1123 - 12 = 1111 € / an.

**Comment by stephane-klein** [comment]
Si je compte, 1h de gestion du dossier (envoyer la facture, recouvrement, discussion au téléphone) : 150 € / h

Il reste 1111-150 = 961 €

Si je compte un tech à 300 € de l'heure, ça fait 3h de travail d'hébergement par an.

Si le site web a coûté : 2500 €, ça fait 2 jours de travail.
