### ISSUE TITLE
Quelle est ma définition des mots suivants : Mission, Projet, Objectif, Goal, Epic, Issues, Portfolio management, POC, Spike, Initiative, Ticket…

### ISSUE THREAD

**Issue by stephane-klein** [harobed/personnal-notebook#387]
Voici une liste de mots, de néologismes que j'ai rencontré dans le domaine de la gestion de projets.  

- Mission
- Projet
- Objectif
- "Goal"
- Epic
- Issues
- Portfolio management
- Proof of concept
- Spike
- Initiative 
- Ticket
- Taskforce vs Équipe
- North Star
- Vision
- Product requirements document (PRD)

J'aimerais les utiliser avec plus de précision et pouvoir partager mes définitions aux personnes avec qui je collabore.

Le but de cette issue est de :

- [ ] Rassembler les sources des définitions de ces mots que je trouve sur Internet, Thread ou Livres
- [ ] Parmi toutes les versions des définitions récoltées, lister celle que j'ai choisi de retenir
- [ ] Rédiger des exemples de mon utilisation de ces mots
- [ ] Rédiger un billet pour présenter le résultat de cette étude

**Comment by stephane-klein** [comment]
J'aimerais présenter la différence entre ces notions sous la forme d'un tableau pour bien présenter les différences entre ces notions.

**Comment by stephane-klein** [comment]
> J'aimerais présenter la différence entre ces notions sous la forme d'un tableau pour bien présenter les différences entre ces notions.

https://docs.google.com/spreadsheets/d/1jG-dnpeZdP91ZGZT0ApcTYRqB7f95-vA8u7KzYGCoSs/edit?usp=sharing

**Comment by stephane-klein** [comment]
Définition de Wiktionary du mot [Mission](https://fr.wiktionary.org/wiki/mission) :

> XIVe siècle Du latin "missio (« action d’envoyer »).

> 1. Charge qu'on donne à quelqu'un, avec pleins pouvoirs pour faire quelque chose.

> 2. But de son action

> 3. Envoi d'une ou de pluiseurs personnes pour un but scientifique, militaire ou politique

**Comment by stephane-klein** [comment]
Réponse ChatGPT :

Les termes "Mission", "Projet", "Objectif", "Goal", "Epic" et "North Star" sont souvent utilisés dans le domaine de la gestion, du développement de logiciels et du leadership pour décrire différentes facettes d'une organisation ou d'un projet. Voici les différences entre ces termes :

> 
> 1. **Mission** :
>    - La mission d'une organisation est sa raison d'être fondamentale. C'est une déclaration concise qui définit le but ou la raison d'être de l'organisation, ses valeurs fondamentales et sa vision à long terme.
>    - La mission guide les actions et les décisions de l'organisation et fournit un cadre général pour ses activités.
> 
> 2. **Projet** :
>    - Un projet est une entreprise temporaire entreprise dans le but de créer un produit, un service ou un résultat unique. Il a un début et une fin définis, ainsi que des objectifs spécifiques à atteindre.
>    - Les projets sont généralement réalisés dans le cadre de contraintes spécifiques telles que des délais, des ressources et un budget définis.
> 
> 3. **Objectif** :
>    - Un objectif est un résultat spécifique que l'on cherche à atteindre dans le cadre d'un projet ou d'une activité. Les objectifs sont généralement définis de manière claire, mesurable, atteignable, pertinent et temporellement défini (SMART).
>    - Les objectifs définissent la direction dans laquelle le projet doit progresser et servent de guide pour prendre des décisions et allouer des ressources.
> 
> 4. **Goal** :
>    - En anglais, "goal" est souvent utilisé de manière interchangeable avec "objective". Cependant, dans certains contextes, "goal" peut se référer à un résultat plus général ou à long terme que les objectifs spécifiques. Dans le domaine du football, par exemple, un but est l'objectif final, mais il peut y avoir plusieurs objectifs spécifiques pour y parvenir.
> 
> 5. **Epic** :
>    - Dans le contexte du développement logiciel et de la gestion de projets agiles, un "épic" est une unité de travail importante et souvent complexe qui peut être décomposée en tâches plus petites et plus gérables. Les épics sont généralement associés à des objectifs commerciaux ou des fonctionnalités majeures et peuvent nécessiter plusieurs itérations pour être complétés.
> 
> 6. **North Star** :
>    - La "North Star" (étoile polaire) est un concept utilisé pour décrire un objectif ou un principe directeur fondamental qui guide les actions et les décisions d'une organisation ou d'un projet. C'est souvent un objectif ambitieux et inspirant qui représente l'idéal vers lequel l'organisation aspire à se diriger, et qui peut être utilisé pour aligner les efforts à long terme.
>    
> En résumé, chaque terme a sa propre signification et son propre contexte d'utilisation, mais ils sont tous liés à la réalisation d'objectifs spécifiques dans le cadre d'une mission ou d'un projet plus vaste.
>

**Comment by stephane-klein** [comment]
Article au sujet de "Mission" versus "Vision" : [Énoncés de mission et de vision : définitions et exemples](https://www.atlassian.com/fr/work-management/strategic-planning/mission-and-vision)

**Comment by stephane-klein** [comment]
J'ai découvert cette "Affiche de projet" de Altassian https://www.atlassian.com/fr/team-playbook/plays/project-poster

**Comment by stephane-klein** [comment]
Je présente dans ce commentaire une pensée brute.

- Mission : représente les tâches que l'organisation humaine (société ou équipe ou individu) fait actuellement
  - Issue de level 1 : Projet (qui peut être du type Initiative) (description très très flou)
    - Issue de level 2 : Epic (qui peut être un spike ou un POC ou un objectif neutre) (description floue)
      - Issue de level 3 : Objectif (qui peut être une issue, une tâche, un ticket, un spike, un POC) (description précise)
- Vision == North Star : présente le futur

Ici les mots Projet, Epic, Objectif… permettent simplement de définir de niveau hiérarchique d'une "issue" et indiquent son niveau de précision de description.

**Comment by stephane-klein** [comment]
À ma connaissance, le mot "issue" a une définition très généraliste :

ChatGPT dit :

> Dans le contexte des logiciels de gestion de projet, une "issue" (ou "problème" en français) fait référence à un point spécifique ou à une tâche qui nécessite une attention, une résolution ou un suivi dans le cadre du projet. Les issues peuvent être des bugs à corriger, des fonctionnalités à implémenter, des demandes de nouvelles fonctionnalités, des questions à discuter, etc.
>
> ....
>
> En résumé, dans les logiciels de gestion de projet, une "issue" représente un élément à traiter ou à résoudre dans le cadre du projet, et les fonctionnalités associées permettent de gérer efficacement ces éléments tout au long du cycle de vie du projet.

Je trouve cela très pratique parce que cela évite de se poser des questions du style « Est-ce que ce "truc" est un "projet", un "objectif", une "vision"… ».  
Une issue peut décrire aussi bien une tâche, un objectif, un projet, un bug…

**Comment by stephane-klein** [comment]
Je lis :

- [x]  [How to create a product requirements document (PRD)](https://www.atlassian.com/agile/product-management/requirements)

**Comment by stephane-klein** [comment]
Je lis :

- [x] https://blog.logrocket.com/product-management/what-is-a-product-requirements-document-prd/

**Comment by stephane-klein** [comment]
De mon point de vue, "Product requirements document" est un synonyme d'un "Definition of done" d'un "Projet".

J'aime le concept de ["Pitch"](https://basecamp.com/shapeup/1.5-chapter-06#ingredient-2-appetite) de ShapeUp qui est un document de présentation d'un "Projet" qui inclue la "définition of done" les "Product requirements"…

**Comment by stephane-klein** [comment]
ChatGPT :

> Les termes "objectif" et "projet" sont souvent utilisés dans des contextes similaires mais ils représentent des concepts différents.
> 
> Un "objectif" est un résultat ou une réalisation que l'on cherche à atteindre. Il s'agit d'une cible spécifique que l'on souhaite accomplir. Les objectifs sont généralement définis de manière plus large et à long terme. Par exemple, dans le cadre d'une organisation, un objectif pourrait être d'augmenter les ventes de 20% au cours de l'année prochaine.
> 
> Un "projet", en revanche, est un effort temporaire entrepris pour atteindre un objectif spécifique. Un projet a un début et une fin définis, ainsi que des livrables spécifiques à produire. Contrairement aux objectifs, les projets sont des initiatives concrètes avec des plans, des ressources et des activités spécifiques pour les réaliser. Reprenons l'exemple précédent : pour atteindre l'objectif d'augmenter les ventes de 20%, une organisation pourrait mettre en place un projet de marketing visant à promouvoir ses produits de manière plus efficace.
> 
> En résumé, les objectifs sont des résultats que l'on cherche à atteindre, tandis que les projets sont les moyens concrets et temporaires mis en place pour atteindre ces objectifs. Les deux sont souvent liés, car les projets sont souvent utilisés pour réaliser des objectifs spécifiques.

**Comment by stephane-klein** [comment]
Étymologie de ["Projet"](https://fr.wiktionary.org/wiki/projet) : 

> Du latin [projectum](https://fr.wiktionary.org/wiki/projectum#la) de [projicere](https://fr.wiktionary.org/wiki/projicere) (« jeter quelque chose vers l'avant ») dont est issu [projeter](https://fr.wiktionary.org/wiki/projeter) → voir [pro-](https://fr.wiktionary.org/wiki/pro-#fr) et [jet](https://fr.wiktionary.org/wiki/jet#fr).

Étymologie de ["Objectif"](https://fr.wiktionary.org/wiki/objectif) : 

> Dérivé d’[objet](https://fr.wiktionary.org/wiki/objet) avec le suffixe adjectival [-if](https://fr.wiktionary.org/wiki/-if). Objet est issu du latin [objectum](https://fr.wiktionary.org/wiki/objectum) (« ce qui est placé devant »), participe passé [substantif](https://fr.wiktionary.org/wiki/substantif) [neutre](https://fr.wiktionary.org/wiki/neutre) d’[obicere](https://fr.wiktionary.org/wiki/obicere) ou [objicere](https://fr.wiktionary.org/w/index.php?title=objecere&action=edit&redlink=1) (« [jeter](https://fr.wiktionary.org/wiki/jeter), placer, présenter devant »), formé du verbe [jacere](https://fr.wiktionary.org/wiki/jacere) (« [jeter](https://fr.wiktionary.org/wiki/jeter) ») avec le préfixe [ob-](https://fr.wiktionary.org/wiki/ob-) (« [devant](https://fr.wiktionary.org/wiki/devant) »).

**Comment by stephane-klein** [comment]
Si la caractéristique d'une tâche ou d'une issue est de pouvoir être fermée, alors un objectif ne devrait jamais être une issue ou une tâche.

Un projet peut être une issue ou une tâche, l'objectif est la description du but. Si l'objectif est atteint, alors le projet est clos avec succès, sinon il est clos sans succès.

**Comment by stephane-klein** [comment]
Je me suis demandé pourquoi "Objectif" est présent dans cette liste en description de l'issue.  
Un objectif est le but d'une issue, d'un projet…  
Je pense avoir ma réponse : je pense que ce sont les OKR qui m'ont incité à créer des issues de type "Objectif", alors qu'avec du recul, je pense que cela n'a pas beaucoup de sens :thinking:.
